# Generated by Django 2.2.1 on 2019-05-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepleasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='task_id',
            field=models.TextField(default=''),
        ),
    ]
