# Generated by Django 2.2.1 on 2019-05-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepleasy', '0003_history_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='loss',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
