# Generated by Django 2.2.1 on 2019-05-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepleasy', '0004_history_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='history',
            name='dataset',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='loss',
            field=models.FloatField(default=0.0),
        ),
    ]
