# Generated by Django 2.2.1 on 2019-06-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('deepleasy', '0005_auto_20190525_1950'),
	]

	operations = [
		migrations.AddField(
			model_name='history',
			name='timestamp',
			field=models.IntegerField(default=0),
		),
	]
